POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpZCI6IjVmYTJkZmJkNGMwY2E1MGM2OGMzYTgwNiIsImlhdCI6MTYwNDUxMzU2M30.i6aO06tKwShWjluMJLXjf_Y0rHzFBbjJcEC1U-Ek9oc

{
    "title": "Oikea token", 
    "author": "joku",
    "url": "jokuosote", 
    "id": "5fa2e3c9bded3229c0e1fa87"
}